### ISSUE TITLE
Setup with webpage.

### ISSUE THREAD

**Issue by BleachtheLeach** [knightzac19/NodeJS-ArkService#4]
Hello, I am having issues with setting up a webpage to display the arknode. I have set it up for the standalone. Is there an example of how its set up and displayed on a html page that i could see the code to so i can try and get this to implement. I'm not a front end developer by any means but i know my way around code. 

But like i said i have it installed planned to go standalone have my api key etc just can't get it to do what i would like it to do.

**Comment by Proantagonist** [comment]
Please see this:

https://github.com/knightzac19/NodeJS-ArkService/issues/3

I provided some assistance to another user having a similar question.

**Comment by BleachtheLeach** [comment]
#3 is busy and has asked me to do this for him :D

**Comment by BleachtheLeach** [comment]
i've read over his issue and read everything over and over and honestly i just can't figure out how to call what var for what list. I'm not 100% with nodejs json etc this is a very large project i'm attempting to help out my friend and its a good learning project for me. jquery and bootstrap are as far as i've ever went into web design/development

**Comment by Proantagonist** [comment]
Well if you have zero experience with this, perhaps you should take a short course on them. Trying to do this with the absolute minimal knowledge will guarantee that you have a very difficult time in progressing.

My reply on the other issue is as basic as I can make it without having to go into detail on what should be common knowledge in front-web development.

Once you get the node app running, the rest is all about fetching data with http post requests using your favorite framework. JQuery is the easiest one.

**Comment by BleachtheLeach** [comment]
okay cool thats really what i was confused on because we have the node app running what seems to be perfectly.
